# PBS configuration

# If submitting to a different project to your default, uncomment line below 
# and change project code as appropriate; also set shortpath below
project: nm03

# Force payu to always find, and save, files in this scratch project directory
# (you may need to add the corresponding PBS -l storage flag in sync_data.sh)
shortpath: /scratch/nm03

queue: normalsr
ncpus: 100
jobfs: 1GB
mem: 512GB


walltime: 04:00:00
jobname: NWshelf_01

model: access-om3

exe: access-om3-MOM6
input:
    - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-datm-ESMFmesh.nc
    - /g/data/vk83/configurations/inputs/access-om3/share/meshes/share/2024.09.16/JRA55do-drof-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/hgrid.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/vcoord.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/bathymetry_mod.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/mask_table.18.10x10
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/init_tracers_modified.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/forcing_obc_segment_001.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/forcing_obc_segment_002.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/forcing_obc_segment_003.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/forcing_obc_segment_004.nc

    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/alk_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/caco3bury_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/caco3_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/caco3_sediment_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/detfe_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/detfe_sediment_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/det_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/det_sediment_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/dic_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/dicp_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/dicr_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/fe_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/no3_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/o2_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/pchl_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/phyfe_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/phy_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/zoofe_obc_segment.nc 
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/zoo_obc_segment.nc 
    
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/init_eta.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/init_vel.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/grid_spec.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/ocean_mosaic.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/access-rom3-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/access-rom3-nomask-ESMFmesh.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/dust_DS.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/tz_segment_001.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/tz_segment_002.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/tz_segment_003.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/tz_segment_004.nc    
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/tu_segment_001.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/tu_segment_002.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/tu_segment_003.nc
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/tu_segment_004.nc
    - /g/data/qv56/replicas/input4MIPs/CMIP6Plus/OMIP/MRI/MRI-JRA55-do-1-6-0/
    - /scratch/nm03/ee8016/regional_mom6_configs/NWshelf_01_IAF/five_dye_input.nc # this is the input file for passive tracers



runlog: false
metadata: 
    enable: false

platform:
    nodesize: 104
    nodemem: 512

# userscripts:
#     setup: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/setup.sh
#     archive: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/archive.sh


modules:
    use:
        - /g/data/vk83/modules
        #- /g/data/x77/ahg157/modules
        #- /g/data/x77/ahg157/spack/1.1/release/modules/linux-rocky8-x86_64_v4
        - /g/data/x77/ahg157/spack/1.1/release/modules/linux-rocky8-x86_64
    load:
        - access-om3/2025.08.003-tracers-from-file
        #- access-om3/2025.08.001-tracers-from-file
        - model-tools/mppnccombine-fast        
        - nco/5.0.5
        - fre-nctools/2024.05-1
#collate:
  #restart: true
  #mpi: true
  #walltime: 1:00:00
  #mem: 10GB
  #ncpus: 4
  #queue: normalsr
  #exe: mppnccombine-fast

collate:
    flags: -n4 -m -r
    exe: mppnccombine
    restart: true
    mpi: false
    walltime: 0:30:00
    mem: 30GB
    ncpus: 1
    queue: normalsr
env:
payu_minimum_version: 1.1.6
